# SELECT THE IMAGE
FROM python:3.10-alpine3.20

# SET THE WORKING DIRECTORY
WORKDIR /app

# COPY ALL THE FILES INTO THE WORKING DIRECTORY
COPY . /app

# INSTALL MAKE
RUN apk add --no-cache make

# INSTALL THE CURRENT PACKAGE AND ITS DEPENDENCIES
RUN make dev-install

# TEST THE PACKAGE
ENTRYPOINT ["pytest"]