site_name: gabocutter
repo_url: https://github.com/gabrieltorresgamez/gabocutter
site_url: https://gabrieltorresgamez.github.io/gabocutter
site_description: My cookiecutter template for data science projects.
site_author: Gabriel Torres Gamez
edit_uri: edit/main/docs/
repo_name: gabrieltorresgamez/gabocutter
copyright: Maintained by <a href="https://torres.swiss">Gabriel Torres Gamez</a>.

nav:
  - Home: index.md
  - Features:
      - Linting: features/linting.md
      - Makefile: features/makefile.md
      - Dependency management with uv: features/uv.md
      - Testing with Pytest: features/pytest.md
      - Documentation with MkDocs: features/mkdocs.md
      - Containerization with Docker: features/docker.md
  - Tutorial: tutorial.md
  - Prompt Arguments: prompt_arguments.md
plugins:
  - search
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  feature:
    tabs: true
  palette:
    # Note: Using the system theme works with the insiders version
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#automatic-light-dark-mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: astral-light
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: astral-dark
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/gabrieltorresgamez/gabocutter
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
